default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.1.0'
    hooks:
    - id: pyupgrade
      args: [--py38-plus]
  - repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    - id: flake8
      additional_dependencies:
        - dlint
        - pep8-naming
        - flake8-pie
        - flake8-builtins
        - flake8-simplify
        - flake8-docstrings
        - flake8-import-order
        - flake8-comprehensions
